<?php

return [
    "gender" => ['Male', 'Female', 'Others'],
    "age" => ['Years', 'Months', 'Days'],
    "contact" => ['Owner', 'Employee','Doctor', 'Provider', 'Consumer', 'Agent', 'General'],
    "contact_media" => ['Avatar', 'Signature'],
    "addresses" => ['Present address', 'Permanent address', 'Billing address'],
    "communications" => ["Mobile", "Phone", "Email", "FB"],
    "relations" => ["Father", "Mother", "Brother", "Sister", "Husband", "Wife", "Son", "Daughter"],
    "blood_groups" => ["A+ (A positive)", "A- (A negative)", "B+ (B positive)", "B- (B negative)", "AB+ (AB positive)", "AB- (AB negative)", "O+ (O positive)", "O- (O negative)"],
    "religions" => [
        "Christianity",
        "Islam",
        "Secular/Nonreligious/Agnostic/Atheist",
        "Hinduism",
        "Buddhism",
        "Chinese traditional religion",
        "Ethnic religions",
        "African traditional religions",
        "Sikhism",
        "Spiritism",
        "Judaism",
        "Bahai",
        "Jainism",
        "Shinto",
        "Cao Dai",
        "Zoroastrianism",
        "Tenrikyo",
        "Animism",
        "Neo-Paganism",
        "Unitarian Universalism",
        "Rastafari",
    ],
    'investment_policy' => ['Mudarabah', 'Musharakah'],
    'account_nature' => ['Individual', 'Joint'],
    'withdraw_policy' => [1, 3, 6, 12], // interval in months
    'duration' => [
        '6' => '6 month',
        '12' => '1 year',
        '18' => '1.5 year',
        '24' => '2 year',
        '36' => '3 year',
        '48' => '4 year',
        '60' => '5 year',
        '72' => '6 year',
        '84' => '7 year',
        '96' => '8 year',
        '108' => '9 year',
        '120' => '10 year',
        
    ],
    'installmentType' => [
        '1' => 'Daily',
        '7' => 'Weekly',
        '30' => 'Monthly',
    ],

];